<?php

namespace Shaythamc\LinkManagementBundle\Service;

class BacklinkManager{
	
	protected $database;
	
	public function __construct(Database $database){
		$this->database = $database;
	}
	
	/**
	 * Add a backlink to the Backlinks table
	 * @param array $backlinkArray
	 * @return boolean
	 */
	public function addBacklink($backlinkArray){
		
		// This field is autogenerated by the database
		unset($backlinkArray['backlinkId']);
		unset($backlinkArray['visible']);
		unset($backlinkArray['anchorStatus']);
		unset($backlinkArray['nofollowStatus']);
        unset($backlinkArray['alive']);
		
		// Create a date and format it for the database
		unset($backlinkArray['dateAdded']); // = date("j-n-Y");
		
		// Prepend a colon to each array key to format it for our
		// prepared statement
		$data = array();
		foreach($backlinkArray as $key => $backlinkAttribute){
			
			$data[':' . $key] = $backlinkAttribute;
		
		}
		
		// The query
		$query = 'INSERT INTO Backlinks(name, url, anchor_text, expiration, siteId) VALUES(:name, :url, :anchorText, :expiration, :siteId)';
		
		// Access the database, send the query and update it
		$this->database->update($query, $data);
		
	}
	
	/**
	 * Get all the backlinks
	 * @result array
	 */
	public function getAllBacklinks(){
		$query = 'SELECT * FROM Backlinks';
		return $this->database->retrieve($query);
	}
	
	public function updateBacklink(Request $request, $backlinkId){
		
	}
    
    public function updateAnchortext(){
        
    }
    
    public function updateAnchorStatus($backlinkId, $anchorStatus){
        
        $query = 'UPDATE Backlinks SET anchor_status = :anchorStatus WHERE backlinkId = :backlinkId';
        $data = array(
                    ':anchorStatus' => $anchorStatus,
                    ':backlinkId' => $backlinkId,
            );
        
        $this->database->update($query, $data);
        
    }
    
    public function updateVisible(){
        
    }
    
    public function updateNofollowStatus($backlinkId, $nofollowStatus){
        $query = 'UPDATE Backlinks SET nofollow_status = :nofollowStatus WHERE backlinkId = :backlinkId';
        $data = array(
                    ':nofollowStatus' => $nofollowStatus,
                    ':backlinkId' => $backlinkId,
            );
        
        $this->database->update($query, $data);
    }
    
    public function updateAlive(){
        
    }
    
    public function getAllBacklinkUrls(){
        $query = 'SELECT backlinkId, name, url, siteId FROM Backlinks';
        return $this->database->retrieve($query);
    }
	
}
